app:
  name: 'taxi-service'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'taxi-service'

db:
  host: "localhost"
  port: "5436"
  username: "postgres"
  dbname: "taxidb"
  sslmode: "disable"
